### ISSUE TITLE
X0 undefined in backward pass

### ISSUE THREAD

**Issue by nestordemeure** [sbarratt/torch_cg#4]
X0 seem to be used but undefined in the backward pass of the [current implementation](https://github.com/sbarratt/torch_cg/blob/13f58a9ee5d53e2cd837d1cc9ea87929cac119ee/torch_cg/cg_batch.py#L135).

**Comment by sbarratt** [comment]
Good point. fixed.

**Comment by nestordemeure** [comment]
Note: it might be worth adding a test with an X0.

I am not sure the backward pass works when there is a X0 as it does not return a gradient for X0 (I encountered the bug but it was with a heavily modified version of your code so it might not be relevant).

**Comment by sbarratt** [comment]
It's not meant to return a derivative with respect to X0.
