### ISSUE TITLE
default maximum number of iterations

### ISSUE THREAD

**Issue by nestordemeure** [sbarratt/torch_cg#5]
In [theory](https://en.wikipedia.org/wiki/Conjugate_gradient_method#Convergence_properties), and under the hypothesis that there is no round-off error, the algorithm should converge in n iteration maximum but you default to 5*n for the maximum number of iterations.

Is there a particular reason ?

**Comment by sbarratt** [comment]
Following what scipy does:
https://github.com/scipy/scipy/blob/2774bec15e3cc3d62617c501404c09ad5f27ae1a/scipy/sparse/linalg/isolve/iterative.py#L279
