### ISSUE TITLE
no_grad option

### ISSUE THREAD

**Issue by fabian-sp** [sbarratt/torch_cg#6]
Hi Shane,

I want to use your CG solver for a simple linear system in Pytorch. For my purpose, I only need to solve, but no need to use `backward`. Of course I could do this by converting to `numpy` and back, but using your repo seemed the cleaner solution.

Is there a possibility to include an option to only use `forward` without Pytorch building up the graph? 

Best, Fabian

**Comment by sbarratt** [comment]
Just put

```
with torch.no_grad():
```

Around your code

**Comment by fabian-sp** [comment]
Hi, thanks for the quick answer. I wasn't sure whether that would surpress all graph computation, so thanks for confirming!
